question_data = [
{"category": "Entertainment: Video Games",
 "type": "boolean",
 "difficulty": "easy",
"question": "Peter Molyneux was the founder of Bullfrog Productions.",

"correct_answer": "True",
 "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Luigi is taller than Mario?", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Minecraft can be played with a virtual reality headset.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The end credits sequence in Grand Theft Auto 5 is over half an hour long.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Codemasters is the developer of the Gran Turismo series.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "There are 2 player roles in Trouble in Terrorist Town.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Doki Doki Literature Club was developed in Japan.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}]

